apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-model-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lokesh2201013/small-task/Task-8/ai-model-k8s
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true