apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model
spec:
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
      - name: ai-model
        image: us-central1-docker.pkg.dev/practice-445623/ai-model-repo/ai
        ports:
        - containerPort: 5000

